// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "obslcm_observ_t.h"

static int __obslcm_observ_t_hash_computed;
static uint64_t __obslcm_observ_t_hash;

uint64_t __obslcm_observ_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __obslcm_observ_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = __obslcm_observ_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x8865db7fe4453a7dLL
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __obslcm_observ_t_get_hash(void)
{
    if (!__obslcm_observ_t_hash_computed) {
        __obslcm_observ_t_hash = (int64_t)__obslcm_observ_t_hash_recursive(NULL);
        __obslcm_observ_t_hash_computed = 1;
    }

    return __obslcm_observ_t_hash;
}

int __obslcm_observ_t_encode_array(void *buf, int offset, int maxlen, const obslcm_observ_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].base_lin_vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].base_ang_vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].gravity, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].commands, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].dof_pos, 12);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].dof_vel, 12);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].action, 12);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int obslcm_observ_t_encode(void *buf, int offset, int maxlen, const obslcm_observ_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __obslcm_observ_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __obslcm_observ_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __obslcm_observ_t_encoded_array_size(const obslcm_observ_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __double_encoded_array_size(p[element].base_lin_vel, 3);

        size += __double_encoded_array_size(p[element].base_ang_vel, 3);

        size += __double_encoded_array_size(p[element].gravity, 3);

        size += __double_encoded_array_size(p[element].commands, 3);

        size += __double_encoded_array_size(p[element].dof_pos, 12);

        size += __double_encoded_array_size(p[element].dof_vel, 12);

        size += __double_encoded_array_size(p[element].action, 12);

    }
    return size;
}

int obslcm_observ_t_encoded_size(const obslcm_observ_t *p)
{
    return 8 + __obslcm_observ_t_encoded_array_size(p, 1);
}

int __obslcm_observ_t_decode_array(const void *buf, int offset, int maxlen, obslcm_observ_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].base_lin_vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].base_ang_vel, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].gravity, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].commands, 3);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].dof_pos, 12);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].dof_vel, 12);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].action, 12);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __obslcm_observ_t_decode_array_cleanup(obslcm_observ_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_decode_array_cleanup(p[element].base_lin_vel, 3);

        __double_decode_array_cleanup(p[element].base_ang_vel, 3);

        __double_decode_array_cleanup(p[element].gravity, 3);

        __double_decode_array_cleanup(p[element].commands, 3);

        __double_decode_array_cleanup(p[element].dof_pos, 12);

        __double_decode_array_cleanup(p[element].dof_vel, 12);

        __double_decode_array_cleanup(p[element].action, 12);

    }
    return 0;
}

int obslcm_observ_t_decode(const void *buf, int offset, int maxlen, obslcm_observ_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __obslcm_observ_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __obslcm_observ_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int obslcm_observ_t_decode_cleanup(obslcm_observ_t *p)
{
    return __obslcm_observ_t_decode_array_cleanup(p, 1);
}

int __obslcm_observ_t_clone_array(const obslcm_observ_t *p, obslcm_observ_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __double_clone_array(p[element].base_lin_vel, q[element].base_lin_vel, 3);

        __double_clone_array(p[element].base_ang_vel, q[element].base_ang_vel, 3);

        __double_clone_array(p[element].gravity, q[element].gravity, 3);

        __double_clone_array(p[element].commands, q[element].commands, 3);

        __double_clone_array(p[element].dof_pos, q[element].dof_pos, 12);

        __double_clone_array(p[element].dof_vel, q[element].dof_vel, 12);

        __double_clone_array(p[element].action, q[element].action, 12);

    }
    return 0;
}

obslcm_observ_t *obslcm_observ_t_copy(const obslcm_observ_t *p)
{
    obslcm_observ_t *q = (obslcm_observ_t*) malloc(sizeof(obslcm_observ_t));
    __obslcm_observ_t_clone_array(p, q, 1);
    return q;
}

void obslcm_observ_t_destroy(obslcm_observ_t *p)
{
    __obslcm_observ_t_decode_array_cleanup(p, 1);
    free(p);
}

int obslcm_observ_t_publish(lcm_t *lc, const char *channel, const obslcm_observ_t *p)
{
      int max_data_size = obslcm_observ_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = obslcm_observ_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _obslcm_observ_t_subscription_t {
    obslcm_observ_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void obslcm_observ_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    obslcm_observ_t p;
    memset(&p, 0, sizeof(obslcm_observ_t));
    status = obslcm_observ_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding obslcm_observ_t!!!\n", status);
        return;
    }

    obslcm_observ_t_subscription_t *h = (obslcm_observ_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    obslcm_observ_t_decode_cleanup (&p);
}

obslcm_observ_t_subscription_t* obslcm_observ_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    obslcm_observ_t_handler_t f, void *userdata)
{
    obslcm_observ_t_subscription_t *n = (obslcm_observ_t_subscription_t*)
                       malloc(sizeof(obslcm_observ_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 obslcm_observ_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg obslcm_observ_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int obslcm_observ_t_subscription_set_queue_capacity (obslcm_observ_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int obslcm_observ_t_unsubscribe(lcm_t *lcm, obslcm_observ_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe obslcm_observ_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

